version: '3.8'
services:
  app:
    build: 
      context: .
      target: runner
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@localhost:5432/fundarb?schema=public
    network_mode: host
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fundarb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  funding-rates-worker:
    build:
      context: .
      target: worker
    environment:
      - DATABASE_URL=postgresql://user:password@localhost:5432/fundarb?schema=public
    network_mode: host
    depends_on:
      - postgres
    restart: always

  spreads-worker:
    build:
      context: .
      target: worker
    command: ["node", "--experimental-specifier-resolution=node", "dist/worker/spreads.js"]
    environment:
      - DATABASE_URL=postgresql://user:password@localhost:5432/fundarb?schema=public
    network_mode: host
    depends_on:
      - postgres
    restart: always

  cleanup-worker:
    build:
      context: .
      target: worker
    command: ["node", "--experimental-specifier-resolution=node", "dist/worker/cleanup.js"]
    environment:
      - DATABASE_URL=postgresql://user:password@localhost:5432/fundarb?schema=public
    network_mode: host
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
