version: '3.8'
services:
  app:
    build: 
      context: .
      target: runner
    network_mode: host
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    network_mode: host
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fundarb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  funding-rates-worker:
    build:
      context: .
      target: worker
    network_mode: host
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: always

  spreads-worker:
    build:
      context: .
      target: worker
    network_mode: host
    command: ["node", "--experimental-specifier-resolution=node", "dist/worker/spreads.js"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: always

  cleanup-worker:
    build:
      context: .
      target: worker
    network_mode: host
    command: ["node", "--experimental-specifier-resolution=node", "dist/worker/cleanup.js"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
