version: '3.8'

x-build-args: &build-args
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  BUILDKIT_INLINE_CACHE: 1

services:
  app:
    build: 
      context: .
      target: runner
      args:
        <<: *build-args
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fundarb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  funding-rates-worker:
    build:
      context: .
      target: worker
      args:
        <<: *build-args
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: always

  spreads-worker:
    build:
      context: .
      target: worker
      args:
        <<: *build-args
    command: ["node", "--experimental-specifier-resolution=node", "dist/worker/spreads.js"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: always

  cleanup-worker:
    build:
      context: .
      target: worker
      args:
        <<: *build-args
    command: ["node", "--experimental-specifier-resolution=node", "dist/worker/cleanup.js"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
