version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fundarb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  spreads-worker:
    build: .
    command: npm run worker:spreads
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: always

  cleanup-worker:
    build: .
    command: npm run worker:cleanup
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
